name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 선택: 캐시
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('infrastructure/docker/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps (lint/test)
        run: |
          python -m pip install --upgrade pip
          pip install -r infrastructure/docker/requirements.txt
          # 필요 시 추가: -r infrastructure/docker/requirements-dev.txt
          pip install ruff pytest

      - name: Lint
        run: ruff check .

      - name: Test
        run: pytest -q

  # (선택) 도커 빌드 검증 — 이미지만 로컬 빌드해서 도커파일 검증
  docker-build-check:
    needs: lint-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build mlflow
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infrastructure/docker/Dockerfile.mlflow
          push: false

      - name: Build analysis
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infrastructure/docker/Dockerfile.analysis
          push: false

      - name: Build airflow
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infrastructure/docker/Dockerfile.airflow
          push: false

      - name: Build api
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infrastructure/docker/Dockerfile.fastapi
          push: false

      - name: Build monitoring
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infrastructure/docker/Dockerfile.monitoring
          push: false
